-- Your SQL goes here
CREATE TABLE posts(
  id INTEGER UNSIGNED PRIMARY KEY AUTO_INCREMENT,
  title TEXT NOT NULL,
  body LONGTEXT NOT NULL,
  is_best_answer BOOLEAN NOT NULL DEFAULT false,
  user_id INTEGER UNSIGNED NOT NULL,
  question_post_id INTEGER UNSIGNED,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  FOREIGN KEY (user_id) REFERENCES users(id) ON UPDATE CASCADE ON DELETE CASCADE,
  FOREIGN KEY (question_post_id) REFERENCES posts(id) ON UPDATE CASCADE ON DELETE CASCADE
)
