-- Your SQL goes here
CREATE TABLE users(
  id INTEGER UNSIGNED PRIMARY KEY AUTO_INCREMENT,
  name VARCHAR(128) NOT NULL UNIQUE,
  avatar_url VARCHAR(256) NOT NULL,
  token VARCHAR(64) DEFAULT NULL,
  token_expire TIMESTAMP NULL DEFAULT NULL,
  access_token VARCHAR(64) DEFAULT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
)
